### PR TITLE
Event id access

### PR DESCRIPTION
**Pull request by calispac**
In this pull request. I tried to start a stream of events by event_id.
E.g.

```python
f = File('my_fits.fits.fz')
for event in f.Events['0123456789']:
    pass
```

### CODE REVIEW

**Comment by dneise** [comment]
Okay test are passing. Now the important question:

We have now `MultiZFitsFile` in this pacakge, even though it is in principle only needed by LST. 
LST wanted one more feature, but Etienne and me asked them to implement this feature in their own realm. This gives them more control, quicker updates and all the stuff.

It is implemented here:
https://github.com/FrancaCassol/ctapipe/tree/LST_reader
See their implementation of the class here:
https://github.com/cta-observatory/ctapipe/compare/master...FrancaCassol:LST_reader#diff-7ad60b3db59840f960fe09fc516d4d95R158

---

Now the question: Is this feature used by SST1M only? Or is it a feature used by everybody in CTA?

If it is a feature only used by SST1M maybe it would be better to implement this in digicampipe.

**Comment by Etienne12345** [comment]
Both are possible. Cyril argued that he would prefer to have it in protozfits. It seems that minor changes (already there, cyril ? If not please at them before the release...) could make it work for all data models. If it does indeed work out of the box for all data models, I see no reason why not to put it in protozfits. If it currently only works for digicam data, better wait for it to also support lst data before doing any release. For Franca's stuff, it was clearly very much specific to LST. I am of course open for discussion !

**Comment by calispac** [comment]
> We have now MultiZFitsFile in this pacakge, even though it is in principle only needed by LST.
LST wanted one more feature, but Etienne and me asked them to implement this feature in their own realm. This gives them more control, quicker updates and all the stuff.

I can implement the feature discussed in this PR for mulitZfitsFile as well. I "only" need to extend the binary search to all the files. Is this what you asked?

> Now the question: Is this feature used by SST1M only? Or is it a feature used by everybody in CTA? If it is a feature only used by SST1M maybe it would be better to implement this in digicampipe.

I don't understand why we should not have it here if it is used only by few people. For instance you and I use numpy and they are features that we don't use that others do. But it is still in the package. As long as it does not interfere with other users it is fine I suppose. Which I believe it is the case since it is tested for LST, NectarCam, SST-1M camera. See : https://github.com/cta-sst-1m/protozfitsreader/blob/78cc1bd71a4d71b468800eddb91a4ca2e1f79529/protozfits/tests/test_File.py#L57

**Comment by calispac** [comment]
@Etienne12345 
Here is how it is done for the moment to support the different data models : https://github.com/cta-sst-1m/protozfitsreader/blob/78cc1bd71a4d71b468800eddb91a4ca2e1f79529/protozfits/__init__.py#L244

**Comment by Etienne12345** [comment]
I was thinking about indeed the multiple files, + the support of R1 data model (the try/catch that we had discussed earlier). 

For your other point, numpy has many features. They work (most of the time) as expected, whether you use it or not. In this case, if people use other data models, they'll be like "oh great I can get events by event id !" try it, and it won't work at all unless their data model is taken into account: for these specific cases we specifically developped digicampipe / lstcampipe / ....

**Comment by Etienne12345** [comment]
Oh and no need to show me the code: I trust what you write in the chat ! It is only a matter of deciding what we put where / why

**Comment by dneise** [comment]
>> We have now MultiZFitsFile in this pacakge, even though it is in principle only needed by LST. LST wanted one more feature, but Etienne and me asked them to implement this feature in their own realm. This gives them more control, quicker updates and all the stuff.

> I can implement the feature discussed in this PR for mulitZfitsFile as well. I "only" need to extend the binary search to all the files. Is this what you asked?

No! I was talking about the question: 

Should a feature be part of "protozfits.File" if it only works on very very special protozfits files, so that **most** people who try it out will get an exception and only **few** will get what they expect.

**Comment by dneise** [comment]
To my understanding the answer by Etienne was: 

This feature is **potentially** useful for many people and therefore it should be implemented here.
I am fine with that and I am happy we established this point.

**Comment by dneise** [comment]
> I don't understand why we should not have it here if it is used only by few people. For instance you and I use numpy and they are features that we don't use that others do. But it is still in the package.

I believe this argument can be extended to allow the inclusion of everything into everything. 
With this argument people could put the entire `requests` package into `numpy`.

I think `MultiZFitsFiles` is a nice example. When it was first introduced, people who were not aware of the special way LST is storing their events, namely interspersed in multiple files in parallel. One user assumed `MultiZFitsFiles` is simply a way to read the evens from many files in a *serial* way, while in reality these `MultiZFitsFiles` takes great care to present the events in rising order from multiple files.

So putting this class into the package `protozfits` confused some people. This is clearly not what we want ... confusing people, right?

**Comment by dneise** [comment]
I believe the purpose of this package is to wrap the protozfits library written and implemented by Etienne in the CamerasToACTL svn repo. 

We **added** a kind of pythonification to this. So it already deviated from being a clear and transparent wrapper. E.g. one can iterate the thing, instead of calling repeatedly [`ProtobufIFits::readMessage(number)`](https://forge.in2p3.fr/projects/ctaactl/repository/entry/CamerasToACTL/trunk/IO/Fits/ProtobufIFits.h#L86) and counting up `number` by ourselves. 

So we have **changed** the interface of the `ProtobufIFits` class which is the original interface to the zfits files. This change in my opinion is both bad and good. It is bad, because this creates a break between Pythonistas and C++-authors. People have to translate when talking to each other. It is good, because iterating over stuff is very natural in Python. 

I have the feeling one should be very careful about more and more additions. Since it only widens the crack between one group and another group. 

To display what I mean by this "crack": In the past the Python interface lacked certain features, which the C++ interface had. For example it was not possible to have multiple Tables open at the same time. This created a lot of confusion and I exchanged many emails with people because of this.

Doing the inverse: Adding features in Python, which do not exist in the actual C++ implementation of the library can also cause confusion. But it can serve as a test-balloon: Before optimizing the C++ library to efficiently perform a certain action: One could first implement it in the Python interface and see if anybody is actually using it.

I think this is what you propose here and I like it in principle as long as it does not add another `MultiZFitsFiles` which potentially confuses everybody who is not SST1M.

Now again. this is only my personal opinion and I can simply be overridden.

**Comment by dneise** [comment]
Another point to **not** put something here is: Quicker updates.

Due to the fact that `protozfits` is a dependency of more than only digicampipe, I believe it is good to not change the interface too often.

**Comment by dneise** [comment]
I think a more explicit interface would be appropriate here.

So instead of 
```
File.Table[int: index]
File.Table[str: index]
```

one should do
```
File.Table.get_event_by_one_index()
File.Table.get_event_by_another_index()
```

The names are not final of course, but I must admit that these different indices are coming from, or why they even exist. I am searching for the relevant CTA documentation in this regard at the moment

**Comment by dneise** [comment]
Another remark I have regarding adding new features to `protozfits.MultiZFitsFiles`. 

The LST developers, namely Franca Cassol, have just started to branch-off of protozfits.MultiZFitsFiles and develop their own ctapipe.io.....MultiZFitsFiles which contains features they like and need.

They did not derive from the protozfits version, but they used the protozfits version as an example implementation. So they copied what they needed and added what was missing from their point of view.

So when we now add features to protozfits.MultiZFitsFiles it will not immediately improve the LST version.

Just so you are aware of this

**Comment by Etienne12345** [comment]
I must say that Dominik's arguments are quite convincing: given the state of affairs, it sound like a good idea to keep protozfits as simple as possible, so that people can use the base package "as-is" and build on top of it in a separate package (digicampipe/lstpipe). So I'd suggest to put Cyril's latest addition in digicampipe rather than protozfits. I'll write to Franca about the fork, and suggest the same to her.

**Pull request closed without merging**
