### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by calispac**
Changed the path for repo

### CODE REVIEW

**Comment by dneise** [comment]
nice very good.

**Comment by calispac** [comment]
by the way travis is reacting on PR and pushes. So thats why there is two tests running in parallel.
They are basically the same but I think it is better to trigger it with push only ? With push i think it can also make the tests on branches.

**Comment by calispac** [comment]
Actually we did it for PR only in digicampipe

**Comment by dneise** [comment]
This seems to be the default .. we do it like this in all other projects I have ..

**Pull request merged**
