### PR TITLE
Added binaries for python37

### PR DESCRIPTION
**Pull request by Etienne12345**

### CODE REVIEW

**Comment by dneise** [comment]
Cool thanks .. I just let travis execute the tests and merge and make a new release then

**Comment by dneise** [comment]
Ah actually .. I think I will just re-release v.1.4.2 ... since nothing in the code changed ... only the py3.7 support was added.

**Comment by Etienne12345** [comment]
I'd rather wait for the tests to complete: even though nothing changed on our side, python 3.7 might provide surprises, or not: I have not idea

**Comment by dneise** [comment]
Ah, this is in one step now by the Linker: 

https://forge.in2p3.fr/projects/ctaactl/repository/entry/CamerasToACTL/trunk/Resources/build_python_extension/setup.py#L149

I basically add `-Wl,-rpath=$ORIGIN` as gcc compiler options, which in turn will give the `-rpath` part to the linker.

**Comment by dneise** [comment]
Maybe something similar exists for OSX and you can just put it into line 141 of `setup.py`

**Comment by Etienne12345** [comment]
I do it somewhat "by hand" with an explicit statement in the shell script. 

Anyways, I re-uploaded the (hopefully) correct binary for python37. Should I close this pull request and create a new one ?

**Comment by dneise** [comment]
no need to re-open

**Comment by dneise** [comment]
perfect all works .. I'll merge

**Comment by Etienne12345** [comment]
Good. And all the tests passed this time !

**Pull request merged**
